CREATE TABLE IF NOT EXISTS TESTSCHEMA.TESTTABLE16 (
    COL1 VARCHAR,
    COL2 NUMBER,
    COL3 VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS TESTSCHEMA.TESTTABLE457 (
    COL1 VARCHAR,
    COL2 NUMBER,
    COL3 VARCHAR(255)
);